# Site Settings
title: Sam Andreae
email: sandreae@gmail.com
description: >
  The website of Sam Andreae.
baseurl: "/ipns/QmeazZFyLXHX7K931vQr6RqDpF6zAk1cczSN1EQ1FCBb7K"
url: "https://ipfs.io"
destination: "../_ipfs_site"
keep_files: [_subsites]
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
collections:
  - projects