# Site Settings
title: Sam Andreae
email: sandreae@gmail.com
description: "The website of saxophonist Sam Andreae."
baseurl: ""
url: "http://localhost:4000"
future: true
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
collections:
  - projects
  - abw
  - s10c
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
