# Site Settings
title: Sam Andreae
email: sandreae@gmail.com
description: >
  The website of Sam Andreae.
baseurl: ""
url: "www.samandreae.com"
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
collections:
  - projects