# Site Settings
title: Sam Andreae
email: sandreae@gmail.com
description: >
  The website of Sam Andreae.
baseurl: ""
url: "www.samandreae.com"
destination: "../_site"
keep_files: [_subsites]
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
collections:
  - projects
  - abw
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap